name: Test CI

on:
  push:
    branches:
      - main
      - 'dev/**'
  pull_request:
    branches:
      - main
      - 'dev/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l

    steps:
      - name: ğŸ§¾ Checkout code
        uses: actions/checkout@v4

      - name: âš¡ Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yaml
          environment-name: test-env
          cache-environment: true
          init-shell: bash

      - name: ğŸ“¦ Install Poetry
        run: |
          pip install poetry pytest
          poetry --version

      - name: ğŸ› ï¸ Install Python dependencies with Poetry
        run: |
          poetry install

      - name: âœ… Run tests with pytest
        run: |
          poetry run pytest
